src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     */
    private $User;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $Date;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $Total;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetail::class, mappedBy="Ord")
     */
    private $orderDetails;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->Total;
    }

    public function setTotal(int $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setOrd($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getOrd() === $this) {
                $orderDetail->setOrd(null);
            }
        }

        return $this;
    }
}

templates/_footer.html.twig
<footer class="footer container" style="border-top: 1px solid #e2e2e2">
    <section class="clearfix footer__top" style="    font: 14px/18px Helvetica,Arial,'DejaVu Sans','Liberation Sans',Freesans,sans-serif;
    color: #333;
    box-sizing: border-box;
    margin: auto;
    max-width: 1200px;
    width: 100%;
    min-width: 980px;
    position: relative;
    display: block;
    padding: 15px 0 5px;">
        <div class="footer__col" style="    font: 14px/18px Helvetica,Arial,'DejaVu Sans','Liberation Sans',Freesans,sans-serif;
    color: #333;
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    float: left;
    width: 33%;">
            <div>
                <a style="text-decoration: none; color: #333" href="#">Purchase history</a><br>
                <a style="text-decoration: none; color: #333" href="#">Return policies</a><br>
                <a style="text-decoration: none; color: #333" href="#">Learn about installment purchase</a><br>
                <a style="text-decoration: none; color: #333" href="#">Delivery &amp; Payment</a><br>
                <a style="text-decoration: none; color: #333" href="#">Purchase history</a><br>
                <a style="text-decoration: none; color: #333" href="#">Warranty Policy</a><br>
            </div>
        </div>
        <div class="footer__col" style="    font: 14px/18px Helvetica,Arial,'DejaVu Sans','Liberation Sans',Freesans,sans-serif;
    color: #333;
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    float: left;
    width: 33%;">
            <div>
                   <a style="text-decoration: none; color: #333" href="#">Company Introduction</a><br>
                    <a style="text-decoration: none; color: #333" href="#">Recruit</a><br>
                    <a style="text-decoration: none; color: #333" href="#">Suggestions &amp; complaints</a><br>
                    <a style="text-decoration: none; color: #333" href="#">Store Location</a><br>
                    <a style="text-decoration: none; color: #333" href="#">View mobile version</a><br>

            </div>
        </div>
        <div class="footer__col"style="    font: 14px/18px Helvetica,Arial,'DejaVu Sans','Liberation Sans',Freesans,sans-serif;
    color: #333;
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    float: left;
    width: 33%;">
            <div class="f-listtel">
                <p class="f-listtel__title">
                    <strong>Hotline (toll-free)</strong></p>
                <p class="f-listtel__content"><span>Call to buy:</span> <a href="tel:18001060">1800.1060</a> (7:30 - 22:00)
                </p>
                <p class="f-listtel__content"><span>Technical assistance:</span> <a href="tel:18001763">1800.1763</a> (7:30 - 22:00)
                </p>
                <p class="f-listtel__content"><span>Complain:</span> <a href="tel:18001062">1800.1062</a> (8:00 -
                    21:30)</p>
                <p class="f-listtel__content"><span>Insurance:</span> <a href="tel:18001064">1800.1064</a> (8:00 - 21:00)
                </p>
            </div>
        </div>

    </section>
{#        <div class="copyright" style="    font: 14px/18px Helvetica,Arial,'DejaVu Sans','Liberation Sans',Freesans,sans-serif;#}
{#        color: #333;#}
{#        box-sizing: border-box;#}
{#        margin: 0;#}
{#        background-color: #f1f1f1;#}
{#        padding: 15px 0;">#}
{#            <div class="container">#}
{#                <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">#}
{#                    <p class="col-md-4 mb-0 text-muted">© 2022 WebG301 - 0905, Sum</p>#}
{#    #}
{#                    <a href="/"#}
{#                       class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">#}
{#                    </a>#}
{#    #}
{#                    <ul class="nav col-md-4 justify-content-end">#}
{#                        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>#}
{#                        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>#}
{#                    </ul>#}
{#                </footer>#}
{#            </div>#}
{#    #}
{#        </div>#}
</footer>

templates/_nav.html.twig
<div class="container" style="background: linear-gradient(-180deg,#f53d2d, #f63);">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="{{ path('app_product_index') }}"
           class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <img class="card-img-top" src="{{ asset('images/logo.png') }}" alt="Symfony!" style="width: 15%;"/>
        </a>
        <div>
            <ul class="nav nav-pills">
                {% if app.request.get('_route') == 'home' %}
                    <li class="nav-item"><a href="{{ path('home') }}" class="nav-link active"
                                            style="color: white;">Home</a></li>
                {% else %}
                    <li class="nav-item"><a href="{{ path('home') }}" class="nav-link" style="color: white;">Home</a>
                    </li>
                {% endif %}
                {% if app.request.get('_route') == 'about' %}
                    <li class="nav-item"><a href="{{ path('about') }}" class="nav-link active" style="color: white;">About</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a href="{{ path('about') }}" class="nav-link" style="color: white;">About</a>
                    </li>
                {% endif %}
                {% if app.request.get('_route') == 'app_product_index' %}
                    <li class="nav-item"><a style="color: white;" href="{{ path('app_product_index') }}"
                                            class="nav-link active">Products</a></li>
                {% else %}
                    <li class="nav-item"><a style="color: white;" href="{{ path('app_product_index') }}"
                                            class="nav-link">Products</a></li>
                {% endif %}
                {% if app.user %}
                    <li class="nav-item">
                        {% if app.request.get('_route') == 'app_user_show' %}
                            <a class="nav-link active" href=" {{ path('app_user_show', {'id':  app.user.id  }) }}"
                               style="color: white;">Hello {{ app.user.lastname }}</a>
                        {% else %}
                            <a class="nav-link" href=" {{ path('app_user_show', {'id':  app.user.id  }) }}"
                               style="color: white;">Hello {{ app.user.lastname }}</a>
                        {% endif %}
                    </li>
                {% endif %}

                <li class="nav-item">
                    {% if app.request.get('_route') == 'app_login' %}
                        <a href="/{{ app.user ? 'logout' : 'login' }}" class="nav-link active" style="color: white;">
                            {{ app.user ? 'Logout' : 'Login' }}
                        </a>
                    {% else %}

                        <a href="/{{ app.user ? 'logout' : 'login' }}" class="nav-link " style="color: white;">
                            {{ app.user ? 'Logout' : 'Login' }}
                        </a>
                    {% endif %}
                </li>
                {% if app.user is null %}
                    {% if app.request.get('_route') == 'app_register' %}
                        <li class="nav-item"><a href="{{ path('app_register') }}" class="nav-link active"
                                                style="color: white;">Signup</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{{ path('app_register') }}" class="nav-link"
                                                style="color: white;">Signup</a></li>
                    {% endif %}
                {% endif %}
                <li class="nav-item">
                    <a href="{{ path('app_review_cart') }}" class="nav-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white"
                             class="bi bi-cart3" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                    </a>
                </li>

            </ul>
            <br>
            {% if is_granted('ROLE_ADMIN') %}

                <ul class="nav nav-pills">
                    <li class="nav-item"><p class="nav-link" style="color: black;background-color: white">Manage: </p>
                    </li>
                    <li class="nav-item">
                        {% if app.request.get('_route') == 'app_user_index' %}
                    <li class="nav-item"><a href="{{ path('app_user_index') }}" class="nav-link active"
                                            style="color: white;">User</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{{ path('app_user_index') }}" class="nav-link"
                                                style="color: white;">User</a></li>
                    {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if app.request.get('_route') == 'app_product_manage' %}
                    <li class="nav-item"><a href="{{ path('app_product_manage') }}" class="nav-link active"
                                            style="color: white;">Product</a></li>
                {% else %}
                    <li class="nav-item"><a href="{{ path('app_product_manage') }}" class="nav-link"
                                            style="color: white;">Product</a></li>
                    {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if app.request.get('_route') == 'app_brand_index' %}
                    <li class="nav-item"><a href="{{ path('app_brand_index') }}" class="nav-link active"
                                            style="color: white;">Brand</a></li>
                {% else %}
                    <li class="nav-item"><a href="{{ path('app_brand_index') }}" class="nav-link" style="color: white;">Brand</a>
                    </li>
                    {% endif %}
                    </li>

                </ul>
            {% endif %}

        </div>
    </header>


</div>

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
              crossorigin="anonymous">
        {{ encore_entry_link_tags('app') }}
    {% endblock %}


    {% block javascripts %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
                crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
        {{ encore_entry_script_tags('app') }}
    {% endblock %}

</head>
<body>
{{ include('_nav.html.twig') }}
{% block body %}{% endblock %}
{{ include('_footer.html.twig') }}
</body>

</body>
</html>