src/Entity/OrderDetail.php
<?php

namespace App\Entity;

use App\Repository\OrderDetailRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderDetailRepository::class)
 */
class OrderDetail
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="orderDetails")
     */
    private $Ord;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     */
    private $Product;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrd(): ?Order
    {
        return $this->Ord;
    }

    public function setOrd(?Order $Ord): self
    {
        $this->Ord = $Ord;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }
}

templates/cash/review.html.twig
{% extends 'base.html.twig' %}

{% block title %}ReView Cash{% endblock %}
{% block body %}
    {% for orderdetail in orderdetails %}
        <table class="table">
            <tbody>
            <tr>
                <th>Description</th>
                <td>{{ orderdetail.product }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>${{ orderdetail.quantity }}</td>
            </tr>
            </tbody>
        </table>
    {% endfor %}
{% endblock %}